import { Activity, CheckCircle2, CircleAlert, Database, RadioTower, RefreshCw, ServerCog } from "lucide-react";
import { Button } from "../../design-system/Button";
import { Panel } from "../../design-system/Panel";
import { useAppStore } from "../../stores/appStore";
import { PageHeading } from "../common/PageHeading";

export function DiagnosticsPage() {
  const health = useAppStore((state) => state.health);
  const servers = useAppStore((state) => state.servers);
  const upsert = useAppStore((state) => state.upsertServer);
  return <div className="page-stack"><PageHeading eyebrow="OBSERVABILITY" title="Diagnostics" description="Sanitized service health and connection state. Pairing tokens and secrets never appear here." /><div className="diagnostics-grid"><Panel title="Application health" eyebrow={health ? new Date(health.checkedAt).toLocaleTimeString() : "CHECKING"}><HealthRow icon={Database} label="SQLite database" state={health?.database ?? "degraded"} /><HealthRow icon={RadioTower} label="Rust+ manager" state={health?.rustplus ?? "idle"} /><HealthRow icon={Activity} label="Scheduler" state={health?.scheduler ?? "idle"} /><HealthRow icon={ServerCog} label="Notification queue" state={health?.notificationQueue ?? "idle"} /></Panel><Panel title="Connection profiles" eyebrow={`${servers.length} TOTAL`}><div className="diagnostic-server-list">{servers.length === 0 && <p className="muted-copy">No server profiles to diagnose.</p>}{servers.map((server) => <div key={server.id}><span className={`health-light ${server.status === "CONNECTED" ? "healthy" : server.status === "ERROR" ? "degraded" : "idle"}`} /><div><strong>{server.name}</strong><span>{server.statusReason ?? server.status.replaceAll("_", " ")}</span></div><Button compact variant="ghost" disabled={["CONNECTING", "AUTHENTICATING"].includes(server.status)} onClick={() => void window.rcc.connectServer(server.id).then(upsert)}><RefreshCw size={13} /> Retry</Button></div>)}</div></Panel></div><Panel title="Troubleshooting path" eyebrow="CONNECTION RECOVERY"><ol className="troubleshooting"><li><span>1</span><div><strong>Check internet access</strong><p>Confirm Windows has connectivity without changing RCC credentials.</p></div></li><li><span>2</span><div><strong>Confirm Rust+ app port</strong><p>The app port is commonly different from the game server port.</p></div></li><li><span>3</span><div><strong>Repair server pairing</strong><p>Obtain a fresh player token if authentication fails.</p></div></li><li><span>4</span><div><strong>Retry the profile</strong><p>Reconnect only the affected server; other profiles remain active.</p></div></li></ol></Panel></div>;
}

function HealthRow({ icon: Icon, label, state }: { icon: typeof Database; label: string; state: string }) { const good = state === "healthy"; return <div className="health-row"><div className={`health-icon ${good ? "good" : state === "degraded" ? "bad" : "idle"}`}>{good ? <CheckCircle2 size={17} /> : <CircleAlert size={17} />}</div><Icon size={16} /><span>{label}</span><strong>{state}</strong></div>; }
