import { Activity, Archive, Ban, Cable, FileCog, HardDrive, LoaderCircle, Megaphone, PlugZap, Plus, RefreshCw, Save, ServerCog, ShieldAlert, Terminal, Trash2, UserMinus } from "lucide-react";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import type { OwnerMetric, OwnerProfile, ServerOwnerConfig, SuiteState } from "../../../shared/contracts/connectedServices";
import { Button } from "../../design-system/Button";
import { Panel } from "../../design-system/Panel";
import { useAppStore } from "../../stores/appStore";
import { PageHeading } from "../common/PageHeading";

export function ServerOwnerPage() {
  const servers = useAppStore((state) => state.servers); const telemetry = useAppStore((state) => state.telemetry); const setError = useAppStore((state) => state.setError);
  const [suite, setSuite] = useState<SuiteState | null>(null); const [config, setConfig] = useState<ServerOwnerConfig | null>(null);
  const [passwords, setPasswords] = useState<Record<string, string>>({}); const [bridgeToken, setBridgeToken] = useState("");
  const [selectedId, setSelectedId] = useState(""); const [command, setCommand] = useState(""); const [target, setTarget] = useState(""); const [reason, setReason] = useState("");
  const [configText, setConfigText] = useState(""); const [busy, setBusy] = useState(""); const [notice, setNotice] = useState("");
  const refresh = async () => { const value = await window.rcc.getSuiteState(); setSuite(value); setConfig((current) => current ?? structuredClone(value.owner)); setSelectedId((current) => current || value.owner.profiles[0]?.id || ""); };
  useEffect(() => { void refresh().catch((error) => setError(readError(error))); const timer = setInterval(() => void window.rcc.getSuiteState().then((value) => { setSuite(value); setConfig((current) => current ?? structuredClone(value.owner)); }), 2000); return () => clearInterval(timer); }, [setError]);
  const selected = config?.profiles.find((profile) => profile.id === selectedId) ?? null;
  const lines = useMemo(() => suite?.rconLines.filter((line) => !selectedId || line.profileId === selectedId).slice(-150) ?? [], [suite, selectedId]);
  const metrics = useMemo(() => suite?.ownerMetrics.filter((metric) => metric.profileId === selectedId).slice(-30) ?? [], [suite, selectedId]);
  if (!suite || !config) return <div className="suite-loading"><LoaderCircle className="spin" /> Loading Server Owner mode…</div>;

  const run = async (key: string, action: () => Promise<string | void>) => { setBusy(key); setNotice(""); try { const result = await action(); if (result) setNotice(result); await refresh(); } catch (error) { setError(readError(error)); } finally { setBusy(""); } };
  const persistOwner = async () => { const value = await window.rcc.saveServerOwner(config, passwords, bridgeToken || undefined); setSuite(value); setConfig(structuredClone(value.owner)); setPasswords({}); setBridgeToken(""); };
  const save = () => run("save", async () => { await persistOwner(); return "Server Owner settings saved"; });
  const addProfile = () => { const profile: OwnerProfile = { id: crypto.randomUUID(), name: `Server ${config.profiles.length + 1}`, address: "127.0.0.1", port: 28016, serverId: null, autoConnect: false, localServerPath: "", backupPath: "", hasPassword: false }; setConfig({ ...config, profiles: [...config.profiles, profile] }); setSelectedId(profile.id); };
  const updateProfile = (patch: Partial<OwnerProfile>) => { if (!selected) return; setConfig({ ...config, profiles: config.profiles.map((profile) => profile.id === selected.id ? { ...profile, ...patch } : profile) }); };
  const ownerAction = (action: Parameters<typeof window.rcc.ownerAction>[1], needsConfirmation = false) => run(`action-${action}`, async () => { if (!selected) throw new Error("Choose an owner profile"); if (needsConfirmation && !window.confirm(`Confirm ${action} for ${selected.name}?`)) return; await persistOwner(); await window.rcc.ownerAction(selected.id, action, target, reason); return `${action} command sent`; });

  return <div className="page-stack owner-page">
    <PageHeading eyebrow="SEPARATE ADMINISTRATOR WORKSPACE" title="Server Owner mode" description="RCON administration, local configuration and backups, schedules, fleet health, and an authenticated uMod/Oxide event bridge. This module is isolated from normal Rust+ player tools." />
    <div className="owner-warning"><ShieldAlert size={18} /><div><strong>Administrator credentials can control your server.</strong><span>Passwords stay in Windows encrypted storage. Destructive moderation actions require confirmation, and wipe preparation never deletes world files automatically.</span></div><button className={`toggle ${config.enabled ? "on" : ""}`} onClick={() => setConfig({ ...config, enabled: !config.enabled })}><span /></button></div>
    {notice && <div className="suite-notice"><Activity size={16} />{notice}</div>}

    <section className="owner-fleet">
      <header><div><span>FLEET</span><strong>{config.profiles.length} owner profiles</strong></div><Button compact onClick={addProfile}><Plus size={14} /> Add server</Button></header>
      <div>{config.profiles.length ? config.profiles.map((profile) => { const linked = profile.serverId ? servers.find((server) => server.id === profile.serverId) : null; const live = profile.serverId ? telemetry[profile.serverId] : null; const status = suite.rconStatuses[profile.id] ?? "disconnected"; return <button key={profile.id} className={`fleet-card ${profile.id === selectedId ? "selected" : ""}`} onClick={() => setSelectedId(profile.id)}><span className={`fleet-light ${status}`} /><strong>{profile.name}</strong><small>{profile.address}:{profile.port}</small><em>{status}</em><span>{linked?.status ?? "No Rust+ link"} · {live?.players ?? "—"}/{live?.maxPlayers ?? "—"}</span></button>; }) : <div className="suite-empty">Add an RCON profile to start the owner workspace.</div>}</div>
    </section>

    {selected && <div className="owner-grid">
      <Panel title="Connection profile" eyebrow="WEBRCON + LOCAL FILES">
        <div className="suite-fields"><Input label="Display name" value={selected.name} onChange={(name) => updateProfile({ name })} /><Input label="RCON address" value={selected.address} onChange={(address) => updateProfile({ address })} /><NumberInput label="RCON port" value={selected.port} onChange={(port) => updateProfile({ port })} /><label><span>Linked Rust+ server</span><select value={selected.serverId ?? ""} onChange={(event) => updateProfile({ serverId: event.target.value || null })}><option value="">None</option>{servers.map((server) => <option value={server.id} key={server.id}>{server.name}</option>)}</select></label><Secret label={selected.hasPassword ? "Replace RCON password" : "RCON password"} value={passwords[selected.id] ?? ""} onChange={(value) => setPasswords({ ...passwords, [selected.id]: value })} /><PathField label="Folder containing server.cfg" value={selected.localServerPath} onPick={async () => { const value = await window.rcc.chooseDirectory("Choose the folder containing server.cfg"); if (value) updateProfile({ localServerPath: value }); }} /><PathField label="Backup destination" value={selected.backupPath} onPick={async () => { const value = await window.rcc.chooseDirectory("Choose a server backup destination"); if (value) updateProfile({ backupPath: value }); }} /></div>
        <label className="suite-check"><input type="checkbox" checked={selected.autoConnect} onChange={(event) => updateProfile({ autoConnect: event.target.checked })} /> Connect RCON when RCC starts</label>
        <div className="suite-actions"><Button compact onClick={() => void run("connect", async () => { await persistOwner(); await window.rcc.rconConnect(selected.id); return "RCON connected"; })}><Cable size={14} /> Connect</Button><Button compact variant="secondary" onClick={() => void run("disconnect", async () => { await window.rcc.rconDisconnect(selected.id); return "RCON disconnected"; })}>Disconnect</Button><Button compact variant="ghost" onClick={() => { setConfig({ ...config, profiles: config.profiles.filter((profile) => profile.id !== selected.id) }); setSelectedId(config.profiles.find((profile) => profile.id !== selected.id)?.id ?? ""); }}><Trash2 size={14} /> Remove</Button></div>
      </Panel>

      <Panel title="RCON console and live logs" eyebrow="DIRECT ADMIN CONNECTION">
        <div className="rcon-terminal">{lines.length ? lines.map((line, index) => <div key={`${line.createdAt}-${index}`} className={line.type}><time>{new Date(line.createdAt).toLocaleTimeString()}</time><span>{line.type === "input" ? "> " : ""}{line.message}</span></div>) : <div className="terminal-empty">Connect to begin receiving console output.</div>}</div>
        <form className="rcon-compose" onSubmit={(event) => { event.preventDefault(); void run("command", async () => { await persistOwner(); await window.rcc.rconCommand(selected.id, command); setCommand(""); }); }}><input value={command} onChange={(event) => setCommand(event.target.value)} placeholder="Enter a Rust server command…" /><button disabled={!command.trim()}><Terminal size={15} /></button></form>
        <div className="owner-quick"><button onClick={() => void ownerAction("save")}><Save size={14} /> Save</button><button onClick={() => void ownerAction("plugins")}><PlugZap size={14} /> Plugin health</button><button onClick={() => void ownerAction("performance")}><Activity size={14} /> Performance</button><button onClick={() => void ownerAction("restart", true)}><RefreshCw size={14} /> Restart 60s</button></div>
        <PerformanceStrip metrics={metrics} />
      </Panel>

      <Panel title="Player moderation" eyebrow="CONFIRMATION REQUIRED">
        <p className="suite-copy">Use a 15–20 digit Steam ID. Commands are escaped and audit-friendly; free-form command injection is rejected.</p>
        <div className="suite-fields"><Input label="Steam ID" value={target} onChange={setTarget} /><Input label="Reason or announcement" value={reason} onChange={setReason} /></div>
        <div className="moderation-actions"><button onClick={() => void ownerAction("announce")}><Megaphone size={15} /> Announce</button><button onClick={() => void ownerAction("kick", true)}><UserMinus size={15} /> Kick</button><button className="danger" onClick={() => void ownerAction("ban", true)}><Ban size={15} /> Ban</button><button onClick={() => void ownerAction("unban", true)}>Unban</button></div>
      </Panel>

      <Panel title="Server configuration" eyebrow="BACKUP BEFORE WRITE">
        <p className="suite-copy">Reads <code>server.cfg</code> from the configured local folder. Every save creates a timestamped <code>.bak</code> copy first.</p>
        <textarea className="config-editor" value={configText} onChange={(event) => setConfigText(event.target.value)} placeholder="Load server.cfg to edit…" spellCheck={false} />
        <div className="suite-actions"><Button compact variant="secondary" onClick={() => void run("config-load", async () => { await persistOwner(); setConfigText(await window.rcc.readServerConfig(selected.id)); return "Configuration loaded"; })}><FileCog size={14} /> Load</Button><Button compact onClick={() => void run("config-save", async () => { if (!window.confirm("Save server.cfg and create a timestamped backup?")) return; await persistOwner(); await window.rcc.saveServerConfig(selected.id, configText); return "Configuration saved with backup"; })}><Save size={14} /> Save safely</Button></div>
      </Panel>

      <Panel title="Backups and wipe scheduling" eyebrow="LOCAL, RECOVERABLE OPERATIONS">
        <div className="backup-callout"><Archive size={24} /><div><strong>Snapshot the complete configured server folder</strong><span>The destination must be outside the live server directory.</span></div><Button compact onClick={() => void run("backup", async () => { await persistOwner(); return window.rcc.runServerBackup(selected.id); })}><HardDrive size={14} /> Back up now</Button></div>
        <ScheduleForm profileId={selected.id} onAdd={(schedule) => setConfig({ ...config, schedules: [...config.schedules, schedule] })} />
        <div className="schedule-list">{config.schedules.filter((item) => item.profileId === selected.id).map((item) => <article key={item.id}><button className={`toggle ${item.enabled ? "on" : ""}`} onClick={() => setConfig({ ...config, schedules: config.schedules.map((schedule) => schedule.id === item.id ? { ...schedule, enabled: !schedule.enabled } : schedule) })}><span /></button><div><strong>{item.kind.replace("-", " ")}</strong><span>{new Date(item.runAt).toLocaleString()} · {item.repeat}</span></div><button onClick={() => setConfig({ ...config, schedules: config.schedules.filter((schedule) => schedule.id !== item.id) })}><Trash2 size={14} /></button></article>)}</div>
        <p className="owner-safe-note">Wipe preparation performs a backup, save, and announcement. It intentionally does not delete map or player files.</p>
      </Panel>

      <Panel title="uMod/Oxide plugin bridge" eyebrow="AUTHENTICATED EVENT INGEST">
        <div className="service-toggle-row"><span>{config.bridge.enabled ? "Listening" : "Disabled"}</span><button className={`toggle ${config.bridge.enabled ? "on" : ""}`} onClick={() => setConfig({ ...config, bridge: { ...config.bridge, enabled: !config.bridge.enabled } })}><span /></button></div>
        <div className="suite-fields"><label><span>Network access</span><select value={config.bridge.bindAddress} onChange={(event) => setConfig({ ...config, bridge: { ...config.bridge, bindAddress: event.target.value as "127.0.0.1" | "0.0.0.0" } })}><option value="127.0.0.1">This PC only</option><option value="0.0.0.0">Local network</option></select></label><NumberInput label="Port" value={config.bridge.port} onChange={(port) => setConfig({ ...config, bridge: { ...config.bridge, port } })} /><Secret label={config.bridge.hasToken ? "Replace bridge token" : "Bridge token (generated if blank)"} value={bridgeToken} onChange={setBridgeToken} /></div>
        {suite.bridgeUrl && <div className="suite-url"><span>POST {suite.bridgeUrl}</span></div>}
        <div className="bridge-events">{suite.ownerEvents.length ? suite.ownerEvents.slice().reverse().map((event) => <article key={event.id} className={event.severity}><time>{new Date(event.createdAt).toLocaleTimeString()}</time><div><strong>{event.title}</strong><span>{event.message}</span></div></article>) : <div className="suite-empty">No bridge events received this session.</div>}</div>
      </Panel>
    </div>}

    <div className="suite-savebar"><span><ServerCog size={16} /> Owner mode is optional and disabled by default.</span><Button onClick={() => void save()} disabled={Boolean(busy)}>{busy === "save" ? <LoaderCircle className="spin" size={15} /> : <Save size={15} />} Save owner workspace</Button></div>
  </div>;
}

function ScheduleForm({ profileId, onAdd }: { profileId: string; onAdd(value: ServerOwnerConfig["schedules"][number]): void }) { const [kind, setKind] = useState<ServerOwnerConfig["schedules"][number]["kind"]>("save"); const [runAt, setRunAt] = useState(""); const [repeat, setRepeat] = useState<ServerOwnerConfig["schedules"][number]["repeat"]>("never"); const submit = (event: FormEvent) => { event.preventDefault(); if (!runAt) return; onAdd({ id: crypto.randomUUID(), profileId, kind, enabled: true, runAt: new Date(runAt).toISOString(), repeat, announceMinutes: kind === "restart" ? [30, 10, 5, 1] : [], announcedMinutes: [], lastRunAt: null }); setRunAt(""); }; return <form className="schedule-form" onSubmit={submit}><select value={kind} onChange={(event) => setKind(event.target.value as typeof kind)}><option value="save">Save</option><option value="backup">Backup</option><option value="restart">Restart</option><option value="wipe-prep">Wipe preparation</option></select><input type="datetime-local" value={runAt} onChange={(event) => setRunAt(event.target.value)} /><select value={repeat} onChange={(event) => setRepeat(event.target.value as typeof repeat)}><option value="never">Once</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select><button><Plus size={14} /> Schedule</button></form>; }
function PerformanceStrip({ metrics }: { metrics: OwnerMetric[] }) { const latest = metrics.at(-1); const points = (key: "fps" | "memoryMb") => { const values = metrics.map((item) => item[key]).filter((value): value is number => value != null); if (!values.length) return ""; const min = Math.min(...values); const max = Math.max(...values); return values.map((value, index) => `${(index / Math.max(1, values.length - 1)) * 100},${30 - ((value - min) / Math.max(1, max - min)) * 26}`).join(" "); }; return <div className="performance-strip"><div><span>FPS</span><strong>{latest?.fps?.toFixed(0) ?? "—"}</strong><svg viewBox="0 0 100 32" preserveAspectRatio="none"><polyline points={points("fps")} /></svg></div><div><span>Memory</span><strong>{latest?.memoryMb != null ? `${latest.memoryMb.toFixed(0)} MB` : "—"}</strong><svg viewBox="0 0 100 32" preserveAspectRatio="none"><polyline points={points("memoryMb")} /></svg></div><div><span>Entities</span><strong>{latest?.entities?.toLocaleString() ?? "—"}</strong></div><div><span>Uptime</span><strong>{latest?.uptimeSeconds != null ? `${Math.floor(latest.uptimeSeconds / 3600)}h` : "—"}</strong></div></div>; }
function Input({ label, value, onChange }: { label: string; value: string; onChange(value: string): void }) { return <label><span>{label}</span><input value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function Secret(props: Parameters<typeof Input>[0]) { return <label><span>{props.label}</span><input type="password" value={props.value} placeholder="Stored encrypted; leave blank to keep" onChange={(event) => props.onChange(event.target.value)} /></label>; }
function NumberInput({ label, value, onChange }: { label: string; value: number; onChange(value: number): void }) { return <label><span>{label}</span><input type="number" min="1" max="65535" value={value} onChange={(event) => onChange(Number(event.target.value))} /></label>; }
function PathField({ label, value, onPick }: { label: string; value: string; onPick(): void }) { return <label><span>{label}</span><div className="path-input"><input value={value} readOnly /><button onClick={onPick}>Browse</button></div></label>; }
function readError(error: unknown): string { return error instanceof Error ? error.message.replace(/^Error invoking remote method '[^']+': /, "") : "Server Owner request failed"; }
